
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 28 17:44:10 EST 2017
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AS = 71;
  public static final int BNOT = 24;
  public static final int BOOL = 74;
  public static final int REAL = 73;
  public static final int GT = 26;
  public static final int READ = 50;
  public static final int GE = 29;
  public static final int PERIOD = 13;
  public static final int SEMI = 9;
  public static final int SIN = 59;
  public static final int EMPTYLIST = 42;
  public static final int COMMA = 11;
  public static final int RBRACE = 6;
  public static final int RPAREN = 4;
  public static final int POW = 21;
  public static final int LT = 27;
  public static final int EQV = 45;
  public static final int INTEGER = 72;
  public static final int LBRACE = 5;
  public static final int LPAREN = 3;
  public static final int LNOT = 31;
  public static final int COSEC = 63;
  public static final int DEF = 49;
  public static final int LE = 28;
  public static final int READINT = 51;
  public static final int THEN = 54;
  public static final int PROC = 43;
  public static final int LOR = 33;
  public static final int EQ = 25;
  public static final int MUL = 18;
  public static final int CHARACTER = 75;
  public static final int PRINTLN = 40;
  public static final int MOD = 20;
  public static final int TAN = 61;
  public static final int CDR = 38;
  public static final int PLOT = 66;
  public static final int PAIRCHECK = 36;
  public static final int PLUS = 16;
  public static final int EQUAL = 46;
  public static final int ASSIGN = 34;
  public static final int VARIABLE = 77;
  public static final int FOR = 68;
  public static final int DIV = 19;
  public static final int ELSE = 53;
  public static final int EOF = 0;
  public static final int BAND = 22;
  public static final int PRINT = 39;
  public static final int BOR = 23;
  public static final int MINUS = 17;
  public static final int IN = 67;
  public static final int error = 1;
  public static final int PAIR = 35;
  public static final int LIST = 41;
  public static final int IF = 52;
  public static final int COLON = 10;
  public static final int LSTCONCAT = 2;
  public static final int SEC = 62;
  public static final int RBRACKET = 8;
  public static final int LAZY = 48;
  public static final int LIMIT = 70;
  public static final int CASE = 55;
  public static final int RVEC = 15;
  public static final int STRING = 76;
  public static final int SIZE = 56;
  public static final int CAR = 37;
  public static final int BE = 58;
  public static final int NEQ = 30;
  public static final int LAND = 32;
  public static final int SUBSTR = 44;
  public static final int LBRACKET = 7;
  public static final int LET = 57;
  public static final int NEG = 12;
  public static final int CALL = 47;
}

