
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 02 21:31:24 EST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 26;
  public static final int POW = 17;
  public static final int CONCAT = 55;
  public static final int PERIOD = 11;
  public static final int READINT = 38;
  public static final int CASE = 54;
  public static final int CAR = 33;
  public static final int INTEGER = 56;
  public static final int NOTEQUAL = 30;
  public static final int CDR = 34;
  public static final int LPAREN = 2;
  public static final int SEMI = 10;
  public static final int PRINTLN = 36;
  public static final int PAIRCHECK = 32;
  public static final int LCBRACE = 6;
  public static final int MINUS = 13;
  public static final int RCBRACE = 7;
  public static final int RPAREN = 3;
  public static final int LESSEQUAL = 28;
  public static final int LESSTHAN = 27;
  public static final int LAZY = 43;
  public static final int COMMA = 8;
  public static final int CALL = 42;
  public static final int BAND = 19;
  public static final int DIV = 15;
  public static final int BNOT = 21;
  public static final int PLUS = 12;
  public static final int IF = 51;
  public static final int ASSIGN = 18;
  public static final int EOF = 0;
  public static final int EQUAL = 25;
  public static final int SIZE = 48;
  public static final int ISEQUAL = 46;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int or = 24;
  public static final int MOD = 16;
  public static final int PAIR = 31;
  public static final int GREATEREQUAL = 29;
  public static final int COLON = 9;
  public static final int ISEQUIVALENT = 47;
  public static final int ELSE = 53;
  public static final int BOR = 20;
  public static final int LBRACE = 4;
  public static final int VARIABLE = 57;
  public static final int READ = 37;
  public static final int LIST = 39;
  public static final int SUBSTR = 40;
  public static final int LET = 44;
  public static final int THEN = 52;
  public static final int RBRACE = 5;
  public static final int LVECTOR = 49;
  public static final int and = 23;
  public static final int not = 22;
  public static final int RVECTOR = 50;
  public static final int PROC = 41;
  public static final int DEF = 45;
  public static final int PRINT = 35;
}

